import type { CatalogueArtifact } from '../src/schema';
import { canonicalJson } from '../src/artifact';

/** Render the checked-in typed module without touching the filesystem. */
export function renderGeneratedCatalogueModule(artifact: CatalogueArtifact): string {
  return `// Generated by packages/catalogue/scripts/catalogue-build.ts. Do not edit by hand.
import type { CatalogueArtifact } from '../schema';

// prettier-ignore
export const generatedCatalogueArtifact: CatalogueArtifact = ${canonicalJson(artifact)};
`;
}

export function renderGeneratedCatalogueJson(artifact: CatalogueArtifact): string {
  return `${canonicalJson(artifact)}\n`;
}
