import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { CATALOGUE_ARTIFACT_SCHEMA_VERSION, catalogueManifest } from '../src/schema.js';
import {
  canonicalJson,
  createCatalogueArtifact,
  validateCatalogueArtifact,
} from '../src/artifact.js';
import type { CatalogueArtifact, CatalogueTrustedKey } from '../src/schema.js';
import { sourceCatalogue } from '../src/source.js';

type BuildMode = 'development' | 'release';

function option(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}

const mode: BuildMode = option('--mode') === 'release' ? 'release' : 'development';
const input = option('--in');
const output = resolve(process.cwd(), option('--out') ?? 'src/generated/catalogue-artifact.ts');
const jsonOutput = resolve(process.cwd(), option('--json-out') ?? 'dist/catalogue.artifact.json');

let artifact: CatalogueArtifact | undefined;
if (input !== undefined) {
  const { readFile } = await import('node:fs/promises');
  artifact = JSON.parse(await readFile(resolve(process.cwd(), input), 'utf8')) as CatalogueArtifact;
  const trustedKeysJson = process.env.ALYTE_CATALOGUE_TRUSTED_KEYS;
  const trustedKeys =
    trustedKeysJson === undefined
      ? undefined
      : (JSON.parse(trustedKeysJson) as readonly CatalogueTrustedKey[]);
  const verification = await validateCatalogueArtifact(artifact, {
    environment: mode,
    trustedKeys,
  });
  if (!verification.ok) {
    console.error(`Catalogue ${mode} build refused: ${verification.reason}`);
    process.exitCode = 1;
  }
} else if (mode === 'release' && catalogueManifest.status !== 'approved') {
  console.error('Catalogue release build refused: content is still review-pending.');
  process.exitCode = 1;
} else {
  artifact = await createCatalogueArtifact(sourceCatalogue, catalogueManifest);
}

if (artifact !== undefined && process.exitCode !== 1) {
  const verification = await validateCatalogueArtifact(artifact, {
    environment: 'development',
  });
  if (!verification.ok) {
    console.error(`Catalogue build refused: ${verification.reason}`);
    process.exitCode = 1;
  } else {
    const generated = `// Generated by packages/catalogue/scripts/catalogue-build.ts. Do not edit by hand.
import type { CatalogueArtifact } from '../schema.js';

// prettier-ignore
export const generatedCatalogueArtifact: CatalogueArtifact = ${canonicalJson(artifact)};

export const generatedCatalogueBuildVerification = {
  schemaVersion: '${CATALOGUE_ARTIFACT_SCHEMA_VERSION}',
  sourceVersion: '${artifact.manifest.version}',
  integrityValidated: true,
  semanticValidated: true,
  signatureValidated: ${artifact.signature !== null},
  reviewStatus: '${artifact.manifest.status}',
} as const;
`;
    await mkdir(dirname(output), { recursive: true });
    await writeFile(output, generated, 'utf8');
    await mkdir(dirname(jsonOutput), { recursive: true });
    await writeFile(jsonOutput, `${canonicalJson(artifact)}\n`, 'utf8');
    console.error(`Catalogue ${mode} artifact emitted to ${output} and ${jsonOutput}`);
  }
}
