import type { BiomarkerCatalogueEntry } from './schema.js';

/** Existing non-lipid comparable families stay isolated from lipid content ownership. */
export const otherComparableBiomarkers: readonly BiomarkerCatalogueEntry[] = [
  {
    id: 'biomarker.hemoglobin',
    aliases: ['hemoglobin', 'hämoglobin', 'hémoglobine', 'hemoglobina', 'emoglobina'],
    specimens: ['blood', 'unknown'],
    units: ['g/dL', 'g/L'],
  },
  {
    id: 'biomarker.hematocrit',
    aliases: [
      'hematocrit',
      'haematocrit',
      'hämatokrit',
      'hématocrite',
      'hematocrito',
      'ematocrito',
      'hematocriet',
      'hematokryt',
    ],
    specimens: ['blood', 'unknown'],
    units: ['%', 'L/L'],
  },
  {
    id: 'biomarker.mcv',
    aliases: [
      'mcv',
      'mean corpuscular volume',
      'mittleres korpuskuläres volumen',
      'volume globulaire moyen',
      'volumen corpuscular medio',
      'volume corpuscolare medio',
      'gemiddeld corpusculair volume',
      'średnia objętość krwinki',
    ],
    specimens: ['blood', 'unknown'],
    units: ['fL'],
  },
  {
    id: 'biomarker.alt',
    aliases: [
      'alt',
      'alanine aminotransferase',
      'alat',
      'alanin-aminotransferase',
      'alanine aminotransférase',
      'alanina aminotransferasa',
      'alanina aminotransferasi',
      'alanine-aminotransferase',
    ],
    specimens: ['blood', 'serum', 'plasma', 'unknown'],
    units: ['U/L'],
  },
  {
    id: 'biomarker.ast',
    aliases: [
      'ast',
      'aspartate aminotransferase',
      'asat',
      'aspartat-aminotransferase',
      'aspartate aminotransférase',
      'aspartato aminotransferasa',
      'aspartato aminotransferasi',
      'aspartaataminotransferase',
    ],
    specimens: ['blood', 'serum', 'plasma', 'unknown'],
    units: ['U/L'],
  },
  {
    id: 'biomarker.ggt',
    aliases: [
      'ggt',
      'gamma-gt',
      'gamma glutamyl transferase',
      'gamma-glutamyltransferase',
      'gamma-glutamyl transférase',
      'gamma glutamil transferasa',
      'gamma glutamil transferasi',
    ],
    specimens: ['blood', 'serum', 'plasma', 'unknown'],
    units: ['U/L'],
  },
];
