// @generated by scripts/generate-local-model-manifest.mjs; do not edit.
import Foundation

enum AlyteLocalModelManifest {
  static let version = "alyte.local-model.manifest.v2"
  static let packID = "qwen3-vl-2b-instruct-q4-k-m"
  static let sourceRepository = "Qwen/Qwen3-VL-2B-Instruct"
  static let sourceRevision = "89644892e4d85e24eaac8bacfd4f463576704203"
  static let artifactRepository = "Qwen/Qwen3-VL-2B-Instruct-GGUF"
  static let artifactRevision = "52d6c8ffea26cc873ac5ad116f8631268d7eb503"
  static let filename = "Qwen3VL-2B-Instruct-Q4_K_M.gguf"
  static let artifactURL = "https://huggingface.co/Qwen/Qwen3-VL-2B-Instruct-GGUF/resolve/52d6c8ffea26cc873ac5ad116f8631268d7eb503/Qwen3VL-2B-Instruct-Q4_K_M.gguf?download=true"
  static let artifactBytes: Int64 = 1_107_409_952
  static let sha256 = "089d75c52f4b7ffc56ba998ffc50aae89fcafc755f9e7208aacca281dca6c2ae"
  static let projectorRepository = "Qwen/Qwen3-VL-2B-Instruct-GGUF"
  static let projectorRevision = "52d6c8ffea26cc873ac5ad116f8631268d7eb503"
  static let projectorFilename = "mmproj-Qwen3VL-2B-Instruct-Q8_0.gguf"
  static let projectorArtifactURL = "https://huggingface.co/Qwen/Qwen3-VL-2B-Instruct-GGUF/resolve/52d6c8ffea26cc873ac5ad116f8631268d7eb503/mmproj-Qwen3VL-2B-Instruct-Q8_0.gguf?download=true"
  static let projectorBytes: Int64 = 445_053_216
  static let projectorSha256 = "f9a68fabba69c3b81e153367b2c7521030b0fa8bb0de400c9599c8e6725f9c82"
  static let bytes: Int64 = 1_552_463_168
  static let publisher = "Qwen"
  static let license = "Apache-2.0"
  static let format = "GGUF"
  static let quantization = "Q4_K_M + Q8_0 projector"
  static let runtimeID = "llama.cpp"
  static let runtimeRepository = "ggml-org/llama.cpp"
  static let runtimeRevision = "bb4caa7540188872173c44d161602d9271386413"
  static let promptBundle = "alyte.document-vlm.prompt.v1"
  static let ocrChunk = "alyte.document-band.v1"
  static let semanticSchema = "alyte.document-vlm.flat-rows.v1"
  static let languages = ["en", "de"]
  static let minimumIOS = "26.0"
  static let minimumFreeBytes: Int64 = 3_500_000_000
  static let minimumMemoryBytes: Int64 = 2_800_000_000
  static let allowedHosts = ["huggingface.co", "cdn-lfs.huggingface.co", "cdn-lfs-us-1.hf.co", "cdn-lfs-eu-1.hf.co", "cdn-lfs.hf.co", "cas-bridge.xethub.hf.co", "us.aws.cdn.hf.co", "us.gcp.cdn.hf.co", "cas-server.xethub.hf.co", "cas-server.xethub-eu.hf.co", "transfer.xethub.hf.co", "transfer.xethub-eu.hf.co"]

  static var expectedURL: URL { URL(string: artifactURL)! }
  static var projectorExpectedURL: URL { URL(string: projectorArtifactURL)! }

  static func publicManifest() -> [String: Any] {
    [
      "manifestVersion": version,
      "pack": [
        "id": packID,
        "source": ["repository": sourceRepository, "revision": sourceRevision],
        "artifact": [
          "repository": artifactRepository,
          "revision": artifactRevision,
          "filename": filename,
          "url": artifactURL,
          "bytes": artifactBytes,
          "sha256": sha256,
        ],
        "projector": [
          "repository": projectorRepository,
          "revision": projectorRevision,
          "filename": projectorFilename,
          "url": projectorArtifactURL,
          "bytes": projectorBytes,
          "sha256": projectorSha256,
        ],
        "bytes": bytes,
        "publisher": publisher,
        "license": license,
        "format": format,
        "quantization": quantization,
      ],
      "runtime": ["id": runtimeID, "repository": runtimeRepository, "revision": runtimeRevision],
      "compatibility": [
        "languages": languages,
        "promptBundle": promptBundle,
        "ocrChunk": ocrChunk,
        "semanticSchema": semanticSchema,
      ],
      "requirements": [
        "minimumIOS": minimumIOS,
        "minimumFreeBytes": minimumFreeBytes,
        "minimumMemoryBytes": minimumMemoryBytes,
      ],
      "allowlist": ["hosts": allowedHosts, "files": [filename, projectorFilename]],
    ]
  }

  static func isAllowedRedirect(_ url: URL) -> Bool {
    guard url.scheme?.lowercased() == "https", let host = url.host?.lowercased(), allowedHosts.contains(host),
          url.user == nil, url.password == nil else { return false }
    return true
  }
}
