// @generated by scripts/generate-semantic-mapper-grammar.mjs; do not edit.
enum AlyteSemanticMapperGrammar {
  static let root = #"""
root ::= "{" ws "\"schemaVersion\"" ws ":" ws "\"alyte.semantic-mapper.v2\"" ws "," ws "\"proposals\"" ws ":" ws proposals ws "}"
proposals ::= "[" ws (proposal (ws "," ws proposal)*)? ws "]"
proposal ::= "{" ws "\"rowKey\"" ws ":" ws string ws "," ws "\"labelKey\"" ws ":" ws string ws "," ws "\"valueKey\"" ws ":" ws string ws "," ws "\"unitKey\"" ws ":" ws nullableString ws "," ws "\"referenceIntervalKey\"" ws ":" ws nullableString ws "," ws "\"flagKey\"" ws ":" ws nullableString ws "," ws "\"role\"" ws ":" ws role ws "," ws "\"specimenType\"" ws ":" ws specimen ws "," ws "\"biomarkerId\"" ws ":" ws (string | "null") ws "}"
nullableString ::= string | "null"
role ::= "\"measurement\"" | "\"preserve\"" | "\"specimen-context\"" | "\"ignore\""
specimen ::= "\"blood\"" | "\"serum\"" | "\"plasma\"" | "\"urine\"" | "\"other\"" | "\"unknown\""
string ::= "\"" ([^"\\] | escape)* "\""
escape ::= "\\" (["\\/bfnrt] | "u" hex4)
hex4 ::= [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F]
ws ::= [ \t\n\r]*
"""#
}
