// @generated by scripts/generate-local-model-manifest.mjs; do not edit.
import Foundation

enum AlyteLocalModelManifest {
  static let version = "alyte.local-model.manifest.v2"
  static let packID = "paddleocr-vl-1.6-q8"
  static let sourceRepository = "SanjeevSOLANKI/PaddleOCR-VL-1.6-GGUF"
  static let sourceRevision = "5621cad76de79b793ae45dbcb48153f12c72a7ac"
  static let artifactRepository = "SanjeevSOLANKI/PaddleOCR-VL-1.6-GGUF"
  static let artifactRevision = "5621cad76de79b793ae45dbcb48153f12c72a7ac"
  static let filename = "PaddleOCR-VL-1.6-Q8_0.gguf"
  static let artifactURL = "https://huggingface.co/SanjeevSOLANKI/PaddleOCR-VL-1.6-GGUF/resolve/5621cad76de79b793ae45dbcb48153f12c72a7ac/PaddleOCR-VL-1.6-Q8_0.gguf?download=true"
  static let artifactBytes: Int64 = 498_316_256
  static let sha256 = "2bda93a416339f2d9f06accae505600544a9e72cc159d0cd1af4c0f679866e1c"
  static let projectorRepository = "SanjeevSOLANKI/PaddleOCR-VL-1.6-GGUF"
  static let projectorRevision = "5621cad76de79b793ae45dbcb48153f12c72a7ac"
  static let projectorFilename = "PaddleOCR-VL-1.6-mmproj.gguf"
  static let projectorArtifactURL = "https://huggingface.co/SanjeevSOLANKI/PaddleOCR-VL-1.6-GGUF/resolve/5621cad76de79b793ae45dbcb48153f12c72a7ac/PaddleOCR-VL-1.6-mmproj.gguf?download=true"
  static let projectorBytes: Int64 = 881_770_560
  static let projectorSha256 = "204d757d7610d9b3faab10d506d69e5b244e32bf765e2bab2d0167e65e0a058a"
  static let bytes: Int64 = 1_380_086_816
  static let publisher = "PaddlePaddle / SanjeevSOLANKI"
  static let license = "Apache-2.0"
  static let format = "GGUF"
  static let quantization = "Q8_0 + F16 projector"
  static let runtimeID = "llama.cpp"
  static let runtimeRepository = "ggml-org/llama.cpp"
  static let runtimeRevision = "bb4caa7540188872173c44d161602d9271386413"
  static let promptBundle = "alyte.document-ocr.raw.v1"
  static let ocrChunk = "alyte.document-band.v1"
  static let semanticSchema = "alyte.paddleocr-vl.flat-rows.v1"
  static let languages = ["en", "de", "lt"]
  static let minimumIOS = "26.0"
  static let minimumFreeBytes: Int64 = 3_500_000_000
  static let minimumMemoryBytes: Int64 = 2_800_000_000
  static let allowedHosts = ["huggingface.co", "cdn-lfs.huggingface.co", "cdn-lfs-us-1.hf.co", "cdn-lfs-eu-1.hf.co", "cdn-lfs.hf.co", "cas-bridge.xethub.hf.co", "us.aws.cdn.hf.co", "us.gcp.cdn.hf.co", "cas-server.xethub.hf.co", "cas-server.xethub-eu.hf.co", "transfer.xethub.hf.co", "transfer.xethub-eu.hf.co"]

  static var expectedURL: URL { URL(string: artifactURL)! }
  static var projectorExpectedURL: URL { URL(string: projectorArtifactURL)! }

  static func publicManifest() -> [String: Any] {
    [
      "manifestVersion": version,
      "pack": [
        "id": packID,
        "source": ["repository": sourceRepository, "revision": sourceRevision],
        "artifact": [
          "repository": artifactRepository,
          "revision": artifactRevision,
          "filename": filename,
          "url": artifactURL,
          "bytes": artifactBytes,
          "sha256": sha256,
        ],
        "projector": [
          "repository": projectorRepository,
          "revision": projectorRevision,
          "filename": projectorFilename,
          "url": projectorArtifactURL,
          "bytes": projectorBytes,
          "sha256": projectorSha256,
        ],
        "bytes": bytes,
        "publisher": publisher,
        "license": license,
        "format": format,
        "quantization": quantization,
      ],
      "runtime": ["id": runtimeID, "repository": runtimeRepository, "revision": runtimeRevision],
      "compatibility": [
        "languages": languages,
        "promptBundle": promptBundle,
        "ocrChunk": ocrChunk,
        "semanticSchema": semanticSchema,
      ],
      "requirements": [
        "minimumIOS": minimumIOS,
        "minimumFreeBytes": minimumFreeBytes,
        "minimumMemoryBytes": minimumMemoryBytes,
      ],
      "allowlist": ["hosts": allowedHosts, "files": [filename, projectorFilename]],
    ]
  }

  static func isAllowedRedirect(_ url: URL) -> Bool {
    guard url.scheme?.lowercased() == "https", let host = url.host?.lowercased(), allowedHosts.contains(host),
          url.user == nil, url.password == nil else { return false }
    return true
  }
}
